name: test

on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable]
        platform:
          #  - { target: x86_64-pc-windows-msvc, os: windows-latest, kind: test }
          #  - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, kind: test }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, kind: bench }
        #  - { target: x86_64-apple-darwin, os: macos-latest, kind: test }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v2
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}

      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libgtksourceview-3.0-dev libappindicator3-dev

      - name: install xvfb and hyperfine (bench only)
        if: matrix.platform.kind == 'bench'
        run: |
          sudo apt-get install -y xvfb
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.11.0/hyperfine_1.11.0_amd64.deb
          sudo dpkg -i hyperfine_1.11.0_amd64.deb

      - name: build wry
        if: matrix.platform.kind != 'bench'
        run: cargo build --target ${{ matrix.platform.target }}

      - name: build tests and examples
        if: matrix.platform.kind != 'bench'
        shell: bash
        run: |
          cargo test --no-run --verbose --target ${{ matrix.platform.target }}
          cargo test --verbose --target ${{ matrix.platform.target }}

      - name: bench
        if: matrix.platform.kind == 'bench'
        run: |
          cargo build --release --example bench_hello_world
          xvfb-run --auto-servernum cargo bench

      - name: Worker info
        if: matrix.kind == 'bench'
        run: |
          cat /proc/cpuinfo
          cat /proc/meminfo
