name: clippy and fmt check

on:
  pull_request:
    paths:
      - '.github/workflows/clippy-fmt.yml'
      - 'src/**'
      - 'Cargo.toml'

jobs:
  clippy_fmt_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings
          name: clippy
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            override: true
            components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
